###生产环境###
server:
  port: ${port:8766}
spring:
  banner:
    location: banner.txt
  application:
    name: user-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #服务发现注册中心地址
feign:
  hystrix:
    enabled: true #开启断路器