server:
  port: ${port:8762} #端口号
spring:
  banner:
    location: braner.txt
  application:
    name: order-server #服务名
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #服务发现注册中心地址
