server:
  port: ${port:8765}
spring:
  application:
    name: web-server
  boot:
    admin:
      client:
        url: http://localhost:8769
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #服务发现注册中心地址
feign:
  hystrix:
    enabled: true #开启断路器
management:
  endpoints:
    web:
      exposure:
        include: "*"